//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunPos.MessageService.Proxy
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageEntity", Namespace="http://schemas.datacontract.org/2004/07/YunPos.MessageService")]
    [System.SerializableAttribute()]
    public partial class MessageEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NoRetryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageType
        {
            get
            {
                return this.MessageTypeField;
            }
            set
            {
                this.MessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NoRetry
        {
            get
            {
                return this.NoRetryField;
            }
            set
            {
                this.NoRetryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Receiver
        {
            get
            {
                return this.ReceiverField;
            }
            set
            {
                this.ReceiverField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="YunPos.MessageService.Proxy.IMessageService", CallbackContract=typeof(YunPos.MessageService.Proxy.IMessageServiceCallback))]
    public interface IMessageService
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessageService/Subscribe")]
        void Subscribe(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessageService/Unsubscribe")]
        void Unsubscribe(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessageService/SendMessage")]
        void SendMessage(YunPos.MessageService.Proxy.MessageEntity message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/SendMessageNeedBack", ReplyAction="http://tempuri.org/IMessageService/SendMessageNeedBackResponse")]
        string SendMessageNeedBack(YunPos.MessageService.Proxy.MessageEntity message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/Ping", ReplyAction="http://tempuri.org/IMessageService/PingResponse")]
        string Ping();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageServiceCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessageService/OnMessageReceived")]
        void OnMessageReceived(YunPos.MessageService.Proxy.MessageEntity message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetData", ReplyAction="http://tempuri.org/IMessageService/GetDataResponse")]
        string GetData(YunPos.MessageService.Proxy.MessageEntity message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageServiceChannel : YunPos.MessageService.Proxy.IMessageService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceClient : System.ServiceModel.DuplexClientBase<YunPos.MessageService.Proxy.IMessageService>, YunPos.MessageService.Proxy.IMessageService
    {
        
        public MessageServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance)
        {
        }
        
        public MessageServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName)
        {
        }
        
        public MessageServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public MessageServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public MessageServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public void Subscribe(string clientId)
        {
            base.Channel.Subscribe(clientId);
        }
        
        public void Unsubscribe(string clientId)
        {
            base.Channel.Unsubscribe(clientId);
        }
        
        public void SendMessage(YunPos.MessageService.Proxy.MessageEntity message)
        {
            base.Channel.SendMessage(message);
        }
        
        public string SendMessageNeedBack(YunPos.MessageService.Proxy.MessageEntity message)
        {
            return base.Channel.SendMessageNeedBack(message);
        }
        
        public string Ping()
        {
            return base.Channel.Ping();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="YunPos.MessageService.Proxy.IPushMessageService")]
    public interface IPushMessageService
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPushMessageService/PushMessage")]
        void PushMessage(YunPos.MessageService.Proxy.MessageEntity message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushMessageService/PushMessageNeedBack", ReplyAction="http://tempuri.org/IPushMessageService/PushMessageNeedBackResponse")]
        string PushMessageNeedBack(YunPos.MessageService.Proxy.MessageEntity message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPushMessageServiceChannel : YunPos.MessageService.Proxy.IPushMessageService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PushMessageServiceClient : System.ServiceModel.ClientBase<YunPos.MessageService.Proxy.IPushMessageService>, YunPos.MessageService.Proxy.IPushMessageService
    {
        
        public PushMessageServiceClient()
        {
        }
        
        public PushMessageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public PushMessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PushMessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PushMessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void PushMessage(YunPos.MessageService.Proxy.MessageEntity message)
        {
            base.Channel.PushMessage(message);
        }
        
        public string PushMessageNeedBack(YunPos.MessageService.Proxy.MessageEntity message)
        {
            return base.Channel.PushMessageNeedBack(message);
        }
    }
}
